"""Static park factors for all 30 MLB parks."""

PARK_FACTORS: dict[str, dict] = {
    "ARI": {"run_factor": 100, "hr_factor": 105, "foul_territory": "medium", "name": "Chase Field"},
    "ATL": {"run_factor": 100, "hr_factor": 103, "foul_territory": "medium", "name": "Truist Park"},
    "BAL": {"run_factor": 107, "hr_factor": 113, "foul_territory": "small",  "name": "Camden Yards"},
    "BOS": {"run_factor": 108, "hr_factor": 104, "foul_territory": "small",  "name": "Fenway Park"},
    "CHC": {"run_factor": 103, "hr_factor": 107, "foul_territory": "small",  "name": "Wrigley Field"},
    "CWS": {"run_factor": 101, "hr_factor": 108, "foul_territory": "medium", "name": "Guaranteed Rate Field"},
    "CIN": {"run_factor": 105, "hr_factor": 113, "foul_territory": "small",  "name": "Great American Ball Park"},
    "CLE": {"run_factor":  97, "hr_factor":  94, "foul_territory": "medium", "name": "Progressive Field"},
    "COL": {"run_factor": 115, "hr_factor": 118, "foul_territory": "medium", "name": "Coors Field"},
    "DET": {"run_factor":  97, "hr_factor":  95, "foul_territory": "large",  "name": "Comerica Park"},
    "HOU": {"run_factor":  98, "hr_factor":  96, "foul_territory": "medium", "name": "Minute Maid Park"},
    "KC":  {"run_factor": 100, "hr_factor": 101, "foul_territory": "large",  "name": "Kauffman Stadium"},
    "LAA": {"run_factor":  99, "hr_factor": 100, "foul_territory": "large",  "name": "Angel Stadium"},
    "LAD": {"run_factor":  95, "hr_factor":  91, "foul_territory": "large",  "name": "Dodger Stadium"},
    "MIA": {"run_factor":  93, "hr_factor":  90, "foul_territory": "medium", "name": "loanDepot Park"},
    "MIL": {"run_factor":  98, "hr_factor":  98, "foul_territory": "medium", "name": "American Family Field"},
    "MIN": {"run_factor": 101, "hr_factor": 107, "foul_territory": "medium", "name": "Target Field"},
    "NYM": {"run_factor":  93, "hr_factor":  95, "foul_territory": "medium", "name": "Citi Field"},
    "NYY": {"run_factor": 106, "hr_factor": 117, "foul_territory": "small",  "name": "Yankee Stadium"},
    "OAK": {"run_factor":  96, "hr_factor":  91, "foul_territory": "large",  "name": "Oakland Coliseum"},
    "PHI": {"run_factor": 103, "hr_factor": 107, "foul_territory": "small",  "name": "Citizens Bank Park"},
    "PIT": {"run_factor":  97, "hr_factor":  96, "foul_territory": "medium", "name": "PNC Park"},
    "SD":  {"run_factor":  93, "hr_factor":  89, "foul_territory": "large",  "name": "Petco Park"},
    "SF":  {"run_factor":  93, "hr_factor":  88, "foul_territory": "medium", "name": "Oracle Park"},
    "SEA": {"run_factor":  95, "hr_factor":  93, "foul_territory": "large",  "name": "T-Mobile Park"},
    "STL": {"run_factor":  98, "hr_factor":  97, "foul_territory": "medium", "name": "Busch Stadium"},
    "TB":  {"run_factor":  97, "hr_factor":  97, "foul_territory": "large",  "name": "Tropicana Field"},
    "TEX": {"run_factor": 102, "hr_factor": 105, "foul_territory": "medium", "name": "Globe Life Field"},
    "TOR": {"run_factor": 103, "hr_factor": 106, "foul_territory": "medium", "name": "Rogers Centre"},
    "WSH": {"run_factor": 100, "hr_factor": 101, "foul_territory": "medium", "name": "Nationals Park"},
}
